### PR TITLE
8275638: GraphKit::combine_exception_states fails with "matching stack sizes" assert

### PR DESCRIPTION
**Pull request by rwestrel**
The bug and fix were discussed in a previous PR:

https://github.com/openjdk/jdk/pull/6572

I pushed all commits from that PR on top of jdk 18 and added a couple
extra tests as suggested in:

https://github.com/openjdk/jdk/pull/6572#issuecomment-994086590

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8275638](https://bugs.openjdk.java.net/browse/JDK-8275638): GraphKit::combine_exception_states fails with "matching stack sizes" assert

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/29/head:pull/29` \
`$ git checkout pull/29`

Update a local copy of the PR: \
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/29/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 29`

View PR using the GUI difftool: \
`$ git pr show -t 29`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/29.diff">https://git.openjdk.java.net/jdk18/pull/29.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]

**Review by vnkozlov — APPROVED** [review]
I agree with this conservative fix. John agreed with it too.
@dean-long please run testing for it before Roland pushed it. Also file RFE to clean these up - we will assign an engineer to look on it later.

**Comment by dean-long** [comment]
I filed JDK-8278873 and started testing.

**Comment by dean-long** [comment]
Test results look good.

**Comment by rwestrel** [comment]
@dean-long @vnkozlov thanks for the reviews.

**Comment by iwanowww** [comment]
I'm late to the party, but still would like to clarify one thing.

It seems the root cause of the bug comes from the fact that the same JVM state is used by both `GraphKit::uncommon_trap()` and `GraphKit::builtin_throw()` while `GraphKit::null_check_receiver_before_call()` deliberately adjusts the state to please the former case. If the original state (after the call) is used for `GraphKit::builtin_throw()`, it should fix the bug as well, shouldn't it?

```
  // Do a null check on the receiver as it would happen before the call to
  // callee (with all arguments still on the stack).
  Node* null_check_receiver_before_call(ciMethod* callee) {
    assert(!callee->is_static(), "must be a virtual method");
    // Callsite signature can be different from actual method being called (i.e _linkTo* sites).
    // Use callsite signature always.
    ciMethod* declared_method = method()->get_method_at_bci(bci());
    const int nargs = declared_method->arg_size();
    inc_sp(nargs);
    Node* n = null_check_receiver();
    dec_sp(nargs);
    return n;
  }
```

**Comment by rwestrel** [comment]
> It seems the root cause of the bug comes from the fact that the same JVM state is used by both `GraphKit::uncommon_trap()` and `GraphKit::builtin_throw()` while `GraphKit::null_check_receiver_before_call()` deliberately adjusts the state to please the former case. If the original state (after the call) is used for `GraphKit::builtin_throw()`, it should fix the bug as well, shouldn't it?

Wouldn't that only work if there's no uncommon trap in GraphKit::builtin_throw()?

**Comment by iwanowww** [comment]
> Wouldn't that only work if there's no uncommon trap in GraphKit::builtin_throw()?

Good point. I overlooked the uncommon trap logic there. 

But my original point still stands: why can't `GraphKit::builtin_throw()` be taught to distinguish between throwing and uncommon trap cases and adjust JVM state accordingly? In this particular case, it seems simpler to start with the JVM state for re-execution (before call) and switch to the JVM state after the call (pop arguments from the stack) when an exception is thrown.

So, instead of checking for local exception handlers and wiping the stack [1], the effects of `null_check_receiver_before_call()` [2] can be undone unconditionally. That should make all possible exception states uniform and, hence, mergeable, shouldn't it?    

[1]
```
       if (!method()->has_exception_handlers()) {
        // We don't need to preserve the stack if there's no handler as the entire frame is going to be popped anyway.
        // This prevents issues with exception handling and late inlining.
        set_sp(0);
        clean_stack(0);
      }
``` 

[2] 
```
  // Do a null check on the receiver as it would happen before the call to
  // callee (with all arguments still on the stack).
  Node* null_check_receiver_before_call(ciMethod* callee) {
    assert(!callee->is_static(), "must be a virtual method");
    // Callsite signature can be different from actual method being called (i.e _linkTo* sites).
    // Use callsite signature always.
    ciMethod* declared_method = method()->get_method_at_bci(bci());
    const int nargs = declared_method->arg_size();
    inc_sp(nargs);
    Node* n = null_check_receiver();
    dec_sp(nargs);
    return n;
  }
```

**Comment by rwestrel** [comment]
> But my original point still stands: why can't `GraphKit::builtin_throw()` be taught to distinguish between throwing and uncommon trap cases and adjust JVM state accordingly? In this particular case, it seems simpler to start with the JVM state for re-execution (before call) and switch to the JVM state after the call (pop arguments from the stack) when an exception is thrown.

Then what's on the stack doesn't matter so why not pop the stack instead?
There's some discussion about that in the initial PR (before the jdk18 fork): https://github.com/openjdk/jdk/pull/6572
And a follow up bug: https://bugs.openjdk.java.net/browse/JDK-8278846

**Comment by iwanowww** [comment]
> Then what's on the stack doesn't matter so why not pop the stack instead?

Yes, that's also an option. (And, probably, the cleanest one.) 

I agree with the summary in JDK-8278846. I don't see any reason why exception state should include stack state. 

Thanks for the clarifications.

**Pull request closed without merging**
