### PR TITLE
8279045: Intrinsics missing vzeroupper instruction

### PR DESCRIPTION
**Pull request by smita-kamath**
Adding vzeroupper instruction to aes and shift intrinsics.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279045](https://bugs.openjdk.java.net/browse/JDK-8279045): Intrinsics missing vzeroupper instruction

### Reviewers
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**) ⚠️ Review applies to f80213905112c5cf65704028fbc49d917a27d3dc
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - **Reviewer**) ⚠️ Review applies to f80213905112c5cf65704028fbc49d917a27d3dc
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/52/head:pull/52` \
`$ git checkout pull/52`

Update a local copy of the PR: \
`$ git checkout pull/52` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/52/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 52`

View PR using the GUI difftool: \
`$ git pr show -t 52`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/52.diff">https://git.openjdk.java.net/jdk18/pull/52.diff</a>

</details>

### CODE REVIEW

**Review by neliasso — APPROVED** [review]
Looks good.

**Review by sviswa7 — APPROVED** [review]
The patch looks good to me.

**Comment by smita-kamath** [comment]
@vnkozlov Could this code change be integrated? Please do advice. 
If it needs testing, would it be possible for you to help me out? Thank you.

**Comment by vnkozlov** [comment]
Please, update to latest changes in JDK18 (there was changes pushed to stubs #19).
I started testing.

**Review by vnkozlov — APPROVED** [review]
Testing passed. Good to integrate.

**Comment by smita-kamath** [comment]
@vnkozlov Thank you.

**Pull request closed without merging**
