### PR TITLE
8279833: Loop optimization issue in String.encodeUTF8_UTF16

### PR DESCRIPTION
**Pull request by cl4es**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8279833](https://bugs.openjdk.java.net/browse/JDK-8279833): Loop optimization issue in String.encodeUTF8_UTF16

### Reviewers
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/99/head:pull/99` \
`$ git checkout pull/99`

Update a local copy of the PR: \
`$ git checkout pull/99` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/99/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 99`

View PR using the GUI difftool: \
`$ git pr show -t 99`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/99.diff">https://git.openjdk.java.net/jdk18/pull/99.diff</a>

</details>

### CODE REVIEW

**Review by RogerRiggs — APPROVED** [review]
LGTM
(This a backport but is using the mainline bug number; already resolved).

**Comment by cl4es** [comment]
> LGTM

Thanks!

> (This a backport but is using the mainline bug number; already resolved).

I think that's intentional? I entered "Backport COMMITHASH" as the PR subject as per instructions and the bots have taken things from there.

**Comment by kevinrushforth** [comment]
> > (This a backport but is using the mainline bug number; already resolved).
> 
> I think that's intentional? I entered "Backport COMMITHASH" as the PR subject as per instructions and the bots have taken things from there.

Yes, it's both intentional and necessary. We only use the JBS bug ID of the main bug, and never the JBS ID of the backport record (presuming the latter is even created ahead of time, which it usually isn't) in pull requests, commit messages, etc.

**Comment by cl4es** [comment]
Thanks for confirming, @kevinrushforth 👍🏽  

While creating the backport bug manually isn't strictly necessary, the bots seem to do the right thing if it exists, so I've taken up the (bad?) habit of creating it manually to keep a tab on my current tasks and intents.

**Comment by kevinrushforth** [comment]
> I've taken up the (bad?) habit of creating it manually to keep a tab on my current tasks and intents.

I do that too in some cases, and for the same reason. The only potential downside is if you create a concrete version for a specific update release and it misses that one and hits the next one, but for that case you can use `NN-pool` as the fixversion on the backport (and Skara will do the right thing).

**Pull request closed without merging**
