### PR TITLE
JDK-8273179: Update nroff pages in JDK 18 before RC

### PR DESCRIPTION
**Pull request by jonathan-gibbons**
Please review this semi-automatic update for the nroff man pages for JDK 18.  The changes update the version number, copyright year, and incorporate the changes from the latest upstream files.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273179](https://bugs.openjdk.java.net/browse/JDK-8273179): Update nroff pages in JDK 18 before RC

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/5/head:pull/5` \
`$ git checkout pull/5`

Update a local copy of the PR: \
`$ git checkout pull/5` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/5/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5`

View PR using the GUI difftool: \
`$ git pr show -t 5`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/5.diff">https://git.openjdk.java.net/jdk18/pull/5.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Jon,

This all looks good - I'm familiar with many of the changes made to the sources but not yet generated.

We will have to be careful not to regress the copyright year or version if any subsequent updates are made before next year, or before the version loses the EA designator.

Thanks,
David

**Comment by jonathan-gibbons** [comment]
Hi David,

The copyright year will naturally sort itself out in a few weeks time ;-)  

When these changes make their way down from 18 to 19, we will probably want to regenerate these files with 19-EA.

-- Jon

**Comment by jonathan-gibbons** [comment]
We will also want to regenerate any appropriate files if any more updates to the man pages are made during the ramp down period.

**Review by irisclark — APPROVED** [review]

**Comment by dholmes-ora** [comment]
Hi @jonathan-gibbons ,

I have a couple of manpage related tasks for early in the 19 release cycle that will take care of updating the version number.

Unfortunately for this change it looks like whomever did the source uodate to the javadoc manpage did not know about the test:

test/langtools/jdk/javadoc/tool/CheckManPageOptions.java

which is now failing on all platforms. :( I will file a bug.

David

**Comment by jonathan-gibbons** [comment]
hmmm, I thought we had taken care of that test. I will investigate

**Pull request closed without merging**
