### PR TITLE
8278125: Some preallocated OOMEs are missing stack trace

### PR DESCRIPTION
**Pull request by y1yang0**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278125](https://bugs.openjdk.java.net/browse/JDK-8278125): Some preallocated OOMEs are missing stack trace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/67/head:pull/67` \
`$ git checkout pull/67`

Update a local copy of the PR: \
`$ git checkout pull/67` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/67/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 67`

View PR using the GUI difftool: \
`$ git pr show -t 67`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/67.diff">https://git.openjdk.java.net/jdk18/pull/67.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Sorry this is a P4 bug (more an enhancement really) and as such is not suitable for inclusion in JDK 18 after RDP1 has started. You could target to 18.0.1 instead.

Thanks,
David

**Comment by y1yang0** [comment]
> Sorry this is a P4 bug (more an enhancement really) and as such is not suitable for inclusion in JDK 18 after RDP1 has started. You could target to 18.0.1 instead.
> 
> Thanks, David

Okay, I will redo this when jdk18 is released...

**Comment by dholmes-ora** [comment]
You can do it now against 18u:

https://github.com/openjdk/jdk18u

**Comment by coleenp** [comment]
I don't see why it should be done in 18u?  The priority wasn't that high.  It should be done on JDK 19 and then backported to JDK 17 (LTS release) and 11 makes more sense to me.

**Comment by coleenp** [comment]
At any rate, the initial fix should be made to JDK 19 and then backported to 18u, 17 and 11, if approved.  The code is going to be different in JDK 11, need to add the strings to the Universe::oops_do function.

**Pull request closed without merging**
