### PR TITLE
8279204: [BACKOUT] JDK-8278413: C2 crash when allocating array of size too large

### PR DESCRIPTION
**Pull request by shipilev**
Summary: This reverts commit deaf75a58587f80046204de7559ff50b3b770bed.

Roland is on vacation now, so we would not get the fix any time soon. Meanwhile, there are lots of test failures and GHA uncleanliness due to this patch.

Additional testing:
 - [x] Test failures from recorded bugs are gone
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug `tier2`
 - [x] Linux x86_64 fastdebug `tier3`
 - [x] GHA are clean

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279204](https://bugs.openjdk.java.net/browse/JDK-8279204): [BACKOUT] JDK-8278413: C2 crash when allocating array of size too large

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18 pull/69/head:pull/69` \
`$ git checkout pull/69`

Update a local copy of the PR: \
`$ git checkout pull/69` \
`$ git pull https://git.openjdk.java.net/jdk18 pull/69/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 69`

View PR using the GUI difftool: \
`$ git pr show -t 69`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18/pull/69.diff">https://git.openjdk.java.net/jdk18/pull/69.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
That seems reasonable. Looks good!

**Comment by shipilev** [comment]
> That seems reasonable. Looks good!

Thanks! Should I wait for 24 hours for this patch, or we consider clean backouts trivial?

**Review by vnkozlov — APPROVED** [review]
No need to wait. Approved.

**Comment by shipilev** [comment]
Thanks.

/integrate

**Pull request closed without merging**
